#!/bin/bash
set -euo pipefail

DOCKER_UID="$(id -u)"
DOCKER_GID="$(id -g)"
IMAGE="${IMAGE:-publiocavalcante/php-laravel:8.3}"

docker build --build-arg UID="${DOCKER_UID}" \
  --build-arg GID="${DOCKER_GID}" \
  -t "${IMAGE}" \
  . \
  --no-cache

docker push "${IMAGE}"
